// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_128_mdc,hls_ip_2019_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-2-i,HLS_INPUT_CLOCK=3.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.291000,HLS_SYN_LAT=259,HLS_SYN_TPT=260,HLS_SYN_MEM=0,HLS_SYN_DSP=384,HLS_SYN_FF=30327,HLS_SYN_LUT=12899,HLS_VERSION=2019_1_1}" *)

module fir_128_mdc (
        n_samples,
        coeff_0,
        coeff_1,
        coeff_2,
        coeff_3,
        coeff_4,
        coeff_5,
        coeff_6,
        coeff_7,
        coeff_8,
        coeff_9,
        coeff_10,
        coeff_11,
        coeff_12,
        coeff_13,
        coeff_14,
        coeff_15,
        coeff_16,
        coeff_17,
        coeff_18,
        coeff_19,
        coeff_20,
        coeff_21,
        coeff_22,
        coeff_23,
        coeff_24,
        coeff_25,
        coeff_26,
        coeff_27,
        coeff_28,
        coeff_29,
        coeff_30,
        coeff_31,
        coeff_32,
        coeff_33,
        coeff_34,
        coeff_35,
        coeff_36,
        coeff_37,
        coeff_38,
        coeff_39,
        coeff_40,
        coeff_41,
        coeff_42,
        coeff_43,
        coeff_44,
        coeff_45,
        coeff_46,
        coeff_47,
        coeff_48,
        coeff_49,
        coeff_50,
        coeff_51,
        coeff_52,
        coeff_53,
        coeff_54,
        coeff_55,
        coeff_56,
        coeff_57,
        coeff_58,
        coeff_59,
        coeff_60,
        coeff_61,
        coeff_62,
        coeff_63,
        coeff_64,
        coeff_65,
        coeff_66,
        coeff_67,
        coeff_68,
        coeff_69,
        coeff_70,
        coeff_71,
        coeff_72,
        coeff_73,
        coeff_74,
        coeff_75,
        coeff_76,
        coeff_77,
        coeff_78,
        coeff_79,
        coeff_80,
        coeff_81,
        coeff_82,
        coeff_83,
        coeff_84,
        coeff_85,
        coeff_86,
        coeff_87,
        coeff_88,
        coeff_89,
        coeff_90,
        coeff_91,
        coeff_92,
        coeff_93,
        coeff_94,
        coeff_95,
        coeff_96,
        coeff_97,
        coeff_98,
        coeff_99,
        coeff_100,
        coeff_101,
        coeff_102,
        coeff_103,
        coeff_104,
        coeff_105,
        coeff_106,
        coeff_107,
        coeff_108,
        coeff_109,
        coeff_110,
        coeff_111,
        coeff_112,
        coeff_113,
        coeff_114,
        coeff_115,
        coeff_116,
        coeff_117,
        coeff_118,
        coeff_119,
        coeff_120,
        coeff_121,
        coeff_122,
        coeff_123,
        coeff_124,
        coeff_125,
        coeff_126,
        coeff_127,
        din_strm_V_TDATA,
        dout_strm_V_TDATA,
        ap_clk,
        ap_rst_n,
        din_strm_V_TVALID,
        din_strm_V_TREADY,
        dout_strm_V_TVALID,
        dout_strm_V_TREADY
);


input  [31:0] n_samples;
input  [31:0] coeff_0;
input  [31:0] coeff_1;
input  [31:0] coeff_2;
input  [31:0] coeff_3;
input  [31:0] coeff_4;
input  [31:0] coeff_5;
input  [31:0] coeff_6;
input  [31:0] coeff_7;
input  [31:0] coeff_8;
input  [31:0] coeff_9;
input  [31:0] coeff_10;
input  [31:0] coeff_11;
input  [31:0] coeff_12;
input  [31:0] coeff_13;
input  [31:0] coeff_14;
input  [31:0] coeff_15;
input  [31:0] coeff_16;
input  [31:0] coeff_17;
input  [31:0] coeff_18;
input  [31:0] coeff_19;
input  [31:0] coeff_20;
input  [31:0] coeff_21;
input  [31:0] coeff_22;
input  [31:0] coeff_23;
input  [31:0] coeff_24;
input  [31:0] coeff_25;
input  [31:0] coeff_26;
input  [31:0] coeff_27;
input  [31:0] coeff_28;
input  [31:0] coeff_29;
input  [31:0] coeff_30;
input  [31:0] coeff_31;
input  [31:0] coeff_32;
input  [31:0] coeff_33;
input  [31:0] coeff_34;
input  [31:0] coeff_35;
input  [31:0] coeff_36;
input  [31:0] coeff_37;
input  [31:0] coeff_38;
input  [31:0] coeff_39;
input  [31:0] coeff_40;
input  [31:0] coeff_41;
input  [31:0] coeff_42;
input  [31:0] coeff_43;
input  [31:0] coeff_44;
input  [31:0] coeff_45;
input  [31:0] coeff_46;
input  [31:0] coeff_47;
input  [31:0] coeff_48;
input  [31:0] coeff_49;
input  [31:0] coeff_50;
input  [31:0] coeff_51;
input  [31:0] coeff_52;
input  [31:0] coeff_53;
input  [31:0] coeff_54;
input  [31:0] coeff_55;
input  [31:0] coeff_56;
input  [31:0] coeff_57;
input  [31:0] coeff_58;
input  [31:0] coeff_59;
input  [31:0] coeff_60;
input  [31:0] coeff_61;
input  [31:0] coeff_62;
input  [31:0] coeff_63;
input  [31:0] coeff_64;
input  [31:0] coeff_65;
input  [31:0] coeff_66;
input  [31:0] coeff_67;
input  [31:0] coeff_68;
input  [31:0] coeff_69;
input  [31:0] coeff_70;
input  [31:0] coeff_71;
input  [31:0] coeff_72;
input  [31:0] coeff_73;
input  [31:0] coeff_74;
input  [31:0] coeff_75;
input  [31:0] coeff_76;
input  [31:0] coeff_77;
input  [31:0] coeff_78;
input  [31:0] coeff_79;
input  [31:0] coeff_80;
input  [31:0] coeff_81;
input  [31:0] coeff_82;
input  [31:0] coeff_83;
input  [31:0] coeff_84;
input  [31:0] coeff_85;
input  [31:0] coeff_86;
input  [31:0] coeff_87;
input  [31:0] coeff_88;
input  [31:0] coeff_89;
input  [31:0] coeff_90;
input  [31:0] coeff_91;
input  [31:0] coeff_92;
input  [31:0] coeff_93;
input  [31:0] coeff_94;
input  [31:0] coeff_95;
input  [31:0] coeff_96;
input  [31:0] coeff_97;
input  [31:0] coeff_98;
input  [31:0] coeff_99;
input  [31:0] coeff_100;
input  [31:0] coeff_101;
input  [31:0] coeff_102;
input  [31:0] coeff_103;
input  [31:0] coeff_104;
input  [31:0] coeff_105;
input  [31:0] coeff_106;
input  [31:0] coeff_107;
input  [31:0] coeff_108;
input  [31:0] coeff_109;
input  [31:0] coeff_110;
input  [31:0] coeff_111;
input  [31:0] coeff_112;
input  [31:0] coeff_113;
input  [31:0] coeff_114;
input  [31:0] coeff_115;
input  [31:0] coeff_116;
input  [31:0] coeff_117;
input  [31:0] coeff_118;
input  [31:0] coeff_119;
input  [31:0] coeff_120;
input  [31:0] coeff_121;
input  [31:0] coeff_122;
input  [31:0] coeff_123;
input  [31:0] coeff_124;
input  [31:0] coeff_125;
input  [31:0] coeff_126;
input  [31:0] coeff_127;
input  [31:0] din_strm_V_TDATA;
output  [31:0] dout_strm_V_TDATA;
input   ap_clk;
input   ap_rst_n;
input   din_strm_V_TVALID;
output   din_strm_V_TREADY;
output   dout_strm_V_TVALID;
input   dout_strm_V_TREADY;

 reg    ap_rst_n_inv;
wire    process_U0_ap_start;
wire    process_U0_ap_done;
wire    process_U0_ap_continue;
wire    process_U0_ap_idle;
wire    process_U0_ap_ready;
wire    process_U0_din_V_TREADY;
wire   [31:0] process_U0_dout_V_TDATA;
wire    process_U0_dout_V_TVALID;
wire    ap_sync_continue;
wire    process_U0_start_full_n;
wire    process_U0_start_write;

process_r process_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(process_U0_ap_start),
    .ap_done(process_U0_ap_done),
    .ap_continue(process_U0_ap_continue),
    .ap_idle(process_U0_ap_idle),
    .ap_ready(process_U0_ap_ready),
    .n_samples(n_samples),
    .filter_coeffs_0(coeff_0),
    .filter_coeffs_1(coeff_1),
    .filter_coeffs_2(coeff_2),
    .filter_coeffs_3(coeff_3),
    .filter_coeffs_4(coeff_4),
    .filter_coeffs_5(coeff_5),
    .filter_coeffs_6(coeff_6),
    .filter_coeffs_7(coeff_7),
    .filter_coeffs_8(coeff_8),
    .filter_coeffs_9(coeff_9),
    .filter_coeffs_10(coeff_10),
    .filter_coeffs_11(coeff_11),
    .filter_coeffs_12(coeff_12),
    .filter_coeffs_13(coeff_13),
    .filter_coeffs_14(coeff_14),
    .filter_coeffs_15(coeff_15),
    .filter_coeffs_16(coeff_16),
    .filter_coeffs_17(coeff_17),
    .filter_coeffs_18(coeff_18),
    .filter_coeffs_19(coeff_19),
    .filter_coeffs_20(coeff_20),
    .filter_coeffs_21(coeff_21),
    .filter_coeffs_22(coeff_22),
    .filter_coeffs_23(coeff_23),
    .filter_coeffs_24(coeff_24),
    .filter_coeffs_25(coeff_25),
    .filter_coeffs_26(coeff_26),
    .filter_coeffs_27(coeff_27),
    .filter_coeffs_28(coeff_28),
    .filter_coeffs_29(coeff_29),
    .filter_coeffs_30(coeff_30),
    .filter_coeffs_31(coeff_31),
    .filter_coeffs_32(coeff_32),
    .filter_coeffs_33(coeff_33),
    .filter_coeffs_34(coeff_34),
    .filter_coeffs_35(coeff_35),
    .filter_coeffs_36(coeff_36),
    .filter_coeffs_37(coeff_37),
    .filter_coeffs_38(coeff_38),
    .filter_coeffs_39(coeff_39),
    .filter_coeffs_40(coeff_40),
    .filter_coeffs_41(coeff_41),
    .filter_coeffs_42(coeff_42),
    .filter_coeffs_43(coeff_43),
    .filter_coeffs_44(coeff_44),
    .filter_coeffs_45(coeff_45),
    .filter_coeffs_46(coeff_46),
    .filter_coeffs_47(coeff_47),
    .filter_coeffs_48(coeff_48),
    .filter_coeffs_49(coeff_49),
    .filter_coeffs_50(coeff_50),
    .filter_coeffs_51(coeff_51),
    .filter_coeffs_52(coeff_52),
    .filter_coeffs_53(coeff_53),
    .filter_coeffs_54(coeff_54),
    .filter_coeffs_55(coeff_55),
    .filter_coeffs_56(coeff_56),
    .filter_coeffs_57(coeff_57),
    .filter_coeffs_58(coeff_58),
    .filter_coeffs_59(coeff_59),
    .filter_coeffs_60(coeff_60),
    .filter_coeffs_61(coeff_61),
    .filter_coeffs_62(coeff_62),
    .filter_coeffs_63(coeff_63),
    .filter_coeffs_64(coeff_64),
    .filter_coeffs_65(coeff_65),
    .filter_coeffs_66(coeff_66),
    .filter_coeffs_67(coeff_67),
    .filter_coeffs_68(coeff_68),
    .filter_coeffs_69(coeff_69),
    .filter_coeffs_70(coeff_70),
    .filter_coeffs_71(coeff_71),
    .filter_coeffs_72(coeff_72),
    .filter_coeffs_73(coeff_73),
    .filter_coeffs_74(coeff_74),
    .filter_coeffs_75(coeff_75),
    .filter_coeffs_76(coeff_76),
    .filter_coeffs_77(coeff_77),
    .filter_coeffs_78(coeff_78),
    .filter_coeffs_79(coeff_79),
    .filter_coeffs_80(coeff_80),
    .filter_coeffs_81(coeff_81),
    .filter_coeffs_82(coeff_82),
    .filter_coeffs_83(coeff_83),
    .filter_coeffs_84(coeff_84),
    .filter_coeffs_85(coeff_85),
    .filter_coeffs_86(coeff_86),
    .filter_coeffs_87(coeff_87),
    .filter_coeffs_88(coeff_88),
    .filter_coeffs_89(coeff_89),
    .filter_coeffs_90(coeff_90),
    .filter_coeffs_91(coeff_91),
    .filter_coeffs_92(coeff_92),
    .filter_coeffs_93(coeff_93),
    .filter_coeffs_94(coeff_94),
    .filter_coeffs_95(coeff_95),
    .filter_coeffs_96(coeff_96),
    .filter_coeffs_97(coeff_97),
    .filter_coeffs_98(coeff_98),
    .filter_coeffs_99(coeff_99),
    .filter_coeffs_100(coeff_100),
    .filter_coeffs_101(coeff_101),
    .filter_coeffs_102(coeff_102),
    .filter_coeffs_103(coeff_103),
    .filter_coeffs_104(coeff_104),
    .filter_coeffs_105(coeff_105),
    .filter_coeffs_106(coeff_106),
    .filter_coeffs_107(coeff_107),
    .filter_coeffs_108(coeff_108),
    .filter_coeffs_109(coeff_109),
    .filter_coeffs_110(coeff_110),
    .filter_coeffs_111(coeff_111),
    .filter_coeffs_112(coeff_112),
    .filter_coeffs_113(coeff_113),
    .filter_coeffs_114(coeff_114),
    .filter_coeffs_115(coeff_115),
    .filter_coeffs_116(coeff_116),
    .filter_coeffs_117(coeff_117),
    .filter_coeffs_118(coeff_118),
    .filter_coeffs_119(coeff_119),
    .filter_coeffs_120(coeff_120),
    .filter_coeffs_121(coeff_121),
    .filter_coeffs_122(coeff_122),
    .filter_coeffs_123(coeff_123),
    .filter_coeffs_124(coeff_124),
    .filter_coeffs_125(coeff_125),
    .filter_coeffs_126(coeff_126),
    .filter_coeffs_127(coeff_127),
    .din_V_TDATA(din_strm_V_TDATA),
    .din_V_TVALID(din_strm_V_TVALID),
    .din_V_TREADY(process_U0_din_V_TREADY),
    .dout_V_TDATA(process_U0_dout_V_TDATA),
    .dout_V_TVALID(process_U0_dout_V_TVALID),
    .dout_V_TREADY(dout_strm_V_TREADY)
);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign din_strm_V_TREADY = process_U0_din_V_TREADY;

assign dout_strm_V_TDATA = process_U0_dout_V_TDATA;

assign dout_strm_V_TVALID = process_U0_dout_V_TVALID;

assign process_U0_ap_continue = 1'b1;

assign process_U0_ap_start = 1'b1;

assign process_U0_start_full_n = 1'b1;

assign process_U0_start_write = 1'b0;

endmodule //fir_128_mdc
