// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dataflow_parent_loop_1 (
        n_particles,
        yaw_TDATA,
        y_TDATA,
        x_TDATA,
        p_distMap_0_address0,
        p_distMap_0_ce0,
        p_distMap_0_d0,
        p_distMap_0_q0,
        p_distMap_0_we0,
        p_distMap_0_address1,
        p_distMap_0_ce1,
        p_distMap_0_d1,
        p_distMap_0_q1,
        p_distMap_0_we1,
        orig_x,
        orig_y,
        map_width,
        map_height,
        map_resolution,
        maxRange,
        p_distMap_1_address0,
        p_distMap_1_ce0,
        p_distMap_1_d0,
        p_distMap_1_q0,
        p_distMap_1_we0,
        p_distMap_1_address1,
        p_distMap_1_ce1,
        p_distMap_1_d1,
        p_distMap_1_q1,
        p_distMap_1_we1,
        p_distMap_2_address0,
        p_distMap_2_ce0,
        p_distMap_2_d0,
        p_distMap_2_q0,
        p_distMap_2_we0,
        p_distMap_2_address1,
        p_distMap_2_ce1,
        p_distMap_2_d1,
        p_distMap_2_q1,
        p_distMap_2_we1,
        p_distMap_3_address0,
        p_distMap_3_ce0,
        p_distMap_3_d0,
        p_distMap_3_q0,
        p_distMap_3_we0,
        p_distMap_3_address1,
        p_distMap_3_ce1,
        p_distMap_3_d1,
        p_distMap_3_q1,
        p_distMap_3_we1,
        p_distMap_4_address0,
        p_distMap_4_ce0,
        p_distMap_4_d0,
        p_distMap_4_q0,
        p_distMap_4_we0,
        p_distMap_4_address1,
        p_distMap_4_ce1,
        p_distMap_4_d1,
        p_distMap_4_q1,
        p_distMap_4_we1,
        rays_TDATA,
        ap_clk,
        ap_rst,
        yaw_TVALID,
        yaw_TREADY,
        y_TVALID,
        y_TREADY,
        x_TVALID,
        x_TREADY,
        orig_x_ap_vld,
        orig_y_ap_vld,
        map_width_ap_vld,
        map_height_ap_vld,
        map_resolution_ap_vld,
        maxRange_ap_vld,
        rays_TVALID,
        rays_TREADY,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] n_particles;
input  [31:0] yaw_TDATA;
input  [31:0] y_TDATA;
input  [31:0] x_TDATA;
output  [17:0] p_distMap_0_address0;
output   p_distMap_0_ce0;
output  [31:0] p_distMap_0_d0;
input  [31:0] p_distMap_0_q0;
output   p_distMap_0_we0;
output  [17:0] p_distMap_0_address1;
output   p_distMap_0_ce1;
output  [31:0] p_distMap_0_d1;
input  [31:0] p_distMap_0_q1;
output   p_distMap_0_we1;
input  [31:0] orig_x;
input  [31:0] orig_y;
input  [31:0] map_width;
input  [31:0] map_height;
input  [31:0] map_resolution;
input  [31:0] maxRange;
output  [17:0] p_distMap_1_address0;
output   p_distMap_1_ce0;
output  [31:0] p_distMap_1_d0;
input  [31:0] p_distMap_1_q0;
output   p_distMap_1_we0;
output  [17:0] p_distMap_1_address1;
output   p_distMap_1_ce1;
output  [31:0] p_distMap_1_d1;
input  [31:0] p_distMap_1_q1;
output   p_distMap_1_we1;
output  [17:0] p_distMap_2_address0;
output   p_distMap_2_ce0;
output  [31:0] p_distMap_2_d0;
input  [31:0] p_distMap_2_q0;
output   p_distMap_2_we0;
output  [17:0] p_distMap_2_address1;
output   p_distMap_2_ce1;
output  [31:0] p_distMap_2_d1;
input  [31:0] p_distMap_2_q1;
output   p_distMap_2_we1;
output  [17:0] p_distMap_3_address0;
output   p_distMap_3_ce0;
output  [31:0] p_distMap_3_d0;
input  [31:0] p_distMap_3_q0;
output   p_distMap_3_we0;
output  [17:0] p_distMap_3_address1;
output   p_distMap_3_ce1;
output  [31:0] p_distMap_3_d1;
input  [31:0] p_distMap_3_q1;
output   p_distMap_3_we1;
output  [17:0] p_distMap_4_address0;
output   p_distMap_4_ce0;
output  [31:0] p_distMap_4_d0;
input  [31:0] p_distMap_4_q0;
output   p_distMap_4_we0;
output  [17:0] p_distMap_4_address1;
output   p_distMap_4_ce1;
output  [31:0] p_distMap_4_d1;
input  [31:0] p_distMap_4_q1;
output   p_distMap_4_we1;
output  [31:0] rays_TDATA;
input   ap_clk;
input   ap_rst;
input   yaw_TVALID;
output   yaw_TREADY;
input   y_TVALID;
output   y_TREADY;
input   x_TVALID;
output   x_TREADY;
input   orig_x_ap_vld;
input   orig_y_ap_vld;
input   map_width_ap_vld;
input   map_height_ap_vld;
input   map_resolution_ap_vld;
input   maxRange_ap_vld;
output   rays_TVALID;
input   rays_TREADY;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg ap_done;
reg ap_ready;
reg ap_idle;

wire   [15:0] dataflow_in_loop_loo_U0_i1_0;
wire   [17:0] dataflow_in_loop_loo_U0_p_distMap_0_address0;
wire    dataflow_in_loop_loo_U0_p_distMap_0_ce0;
wire   [31:0] dataflow_in_loop_loo_U0_p_distMap_0_d0;
wire    dataflow_in_loop_loo_U0_p_distMap_0_we0;
wire   [17:0] dataflow_in_loop_loo_U0_p_distMap_0_address1;
wire    dataflow_in_loop_loo_U0_p_distMap_0_ce1;
wire   [31:0] dataflow_in_loop_loo_U0_p_distMap_0_d1;
wire    dataflow_in_loop_loo_U0_p_distMap_0_we1;
wire   [17:0] dataflow_in_loop_loo_U0_p_distMap_1_address0;
wire    dataflow_in_loop_loo_U0_p_distMap_1_ce0;
wire   [31:0] dataflow_in_loop_loo_U0_p_distMap_1_d0;
wire    dataflow_in_loop_loo_U0_p_distMap_1_we0;
wire   [17:0] dataflow_in_loop_loo_U0_p_distMap_1_address1;
wire    dataflow_in_loop_loo_U0_p_distMap_1_ce1;
wire   [31:0] dataflow_in_loop_loo_U0_p_distMap_1_d1;
wire    dataflow_in_loop_loo_U0_p_distMap_1_we1;
wire   [17:0] dataflow_in_loop_loo_U0_p_distMap_2_address0;
wire    dataflow_in_loop_loo_U0_p_distMap_2_ce0;
wire   [31:0] dataflow_in_loop_loo_U0_p_distMap_2_d0;
wire    dataflow_in_loop_loo_U0_p_distMap_2_we0;
wire   [17:0] dataflow_in_loop_loo_U0_p_distMap_2_address1;
wire    dataflow_in_loop_loo_U0_p_distMap_2_ce1;
wire   [31:0] dataflow_in_loop_loo_U0_p_distMap_2_d1;
wire    dataflow_in_loop_loo_U0_p_distMap_2_we1;
wire   [17:0] dataflow_in_loop_loo_U0_p_distMap_3_address0;
wire    dataflow_in_loop_loo_U0_p_distMap_3_ce0;
wire   [31:0] dataflow_in_loop_loo_U0_p_distMap_3_d0;
wire    dataflow_in_loop_loo_U0_p_distMap_3_we0;
wire   [17:0] dataflow_in_loop_loo_U0_p_distMap_3_address1;
wire    dataflow_in_loop_loo_U0_p_distMap_3_ce1;
wire   [31:0] dataflow_in_loop_loo_U0_p_distMap_3_d1;
wire    dataflow_in_loop_loo_U0_p_distMap_3_we1;
wire   [17:0] dataflow_in_loop_loo_U0_p_distMap_4_address0;
wire    dataflow_in_loop_loo_U0_p_distMap_4_ce0;
wire   [31:0] dataflow_in_loop_loo_U0_p_distMap_4_d0;
wire    dataflow_in_loop_loo_U0_p_distMap_4_we0;
wire   [17:0] dataflow_in_loop_loo_U0_p_distMap_4_address1;
wire    dataflow_in_loop_loo_U0_p_distMap_4_ce1;
wire   [31:0] dataflow_in_loop_loo_U0_p_distMap_4_d1;
wire    dataflow_in_loop_loo_U0_p_distMap_4_we1;
wire   [31:0] dataflow_in_loop_loo_U0_rays_TDATA;
wire    dataflow_in_loop_loo_U0_yaw_TREADY;
wire    dataflow_in_loop_loo_U0_y_TREADY;
wire    dataflow_in_loop_loo_U0_x_TREADY;
wire    dataflow_in_loop_loo_U0_ap_start;
wire    dataflow_in_loop_loo_U0_rays_TVALID;
wire    dataflow_in_loop_loo_U0_ap_done;
wire    dataflow_in_loop_loo_U0_ap_ready;
wire    dataflow_in_loop_loo_U0_ap_idle;
reg    dataflow_in_loop_loo_U0_ap_continue;
wire    ap_sync_continue;
wire    ap_sync_done;
wire    ap_sync_ready;
reg   [31:0] loop_dataflow_input_count;
reg   [31:0] loop_dataflow_output_count;
wire   [31:0] bound_minus_1;
wire    dataflow_in_loop_loo_U0_start_full_n;
wire    dataflow_in_loop_loo_U0_start_write;

// power-on initialization
initial begin
#0 loop_dataflow_input_count = 32'd0;
#0 loop_dataflow_output_count = 32'd0;
end

dataflow_in_loop_loo dataflow_in_loop_loo_U0(
    .yaw_TDATA(yaw_TDATA),
    .i1_0(dataflow_in_loop_loo_U0_i1_0),
    .y_TDATA(y_TDATA),
    .x_TDATA(x_TDATA),
    .p_distMap_0_address0(dataflow_in_loop_loo_U0_p_distMap_0_address0),
    .p_distMap_0_ce0(dataflow_in_loop_loo_U0_p_distMap_0_ce0),
    .p_distMap_0_d0(dataflow_in_loop_loo_U0_p_distMap_0_d0),
    .p_distMap_0_q0(p_distMap_0_q0),
    .p_distMap_0_we0(dataflow_in_loop_loo_U0_p_distMap_0_we0),
    .p_distMap_0_address1(dataflow_in_loop_loo_U0_p_distMap_0_address1),
    .p_distMap_0_ce1(dataflow_in_loop_loo_U0_p_distMap_0_ce1),
    .p_distMap_0_d1(dataflow_in_loop_loo_U0_p_distMap_0_d1),
    .p_distMap_0_q1(32'd0),
    .p_distMap_0_we1(dataflow_in_loop_loo_U0_p_distMap_0_we1),
    .orig_x(orig_x),
    .orig_y(orig_y),
    .map_width(map_width),
    .map_height(map_height),
    .map_resolution(map_resolution),
    .maxRange(maxRange),
    .p_distMap_1_address0(dataflow_in_loop_loo_U0_p_distMap_1_address0),
    .p_distMap_1_ce0(dataflow_in_loop_loo_U0_p_distMap_1_ce0),
    .p_distMap_1_d0(dataflow_in_loop_loo_U0_p_distMap_1_d0),
    .p_distMap_1_q0(p_distMap_1_q0),
    .p_distMap_1_we0(dataflow_in_loop_loo_U0_p_distMap_1_we0),
    .p_distMap_1_address1(dataflow_in_loop_loo_U0_p_distMap_1_address1),
    .p_distMap_1_ce1(dataflow_in_loop_loo_U0_p_distMap_1_ce1),
    .p_distMap_1_d1(dataflow_in_loop_loo_U0_p_distMap_1_d1),
    .p_distMap_1_q1(32'd0),
    .p_distMap_1_we1(dataflow_in_loop_loo_U0_p_distMap_1_we1),
    .p_distMap_2_address0(dataflow_in_loop_loo_U0_p_distMap_2_address0),
    .p_distMap_2_ce0(dataflow_in_loop_loo_U0_p_distMap_2_ce0),
    .p_distMap_2_d0(dataflow_in_loop_loo_U0_p_distMap_2_d0),
    .p_distMap_2_q0(p_distMap_2_q0),
    .p_distMap_2_we0(dataflow_in_loop_loo_U0_p_distMap_2_we0),
    .p_distMap_2_address1(dataflow_in_loop_loo_U0_p_distMap_2_address1),
    .p_distMap_2_ce1(dataflow_in_loop_loo_U0_p_distMap_2_ce1),
    .p_distMap_2_d1(dataflow_in_loop_loo_U0_p_distMap_2_d1),
    .p_distMap_2_q1(32'd0),
    .p_distMap_2_we1(dataflow_in_loop_loo_U0_p_distMap_2_we1),
    .p_distMap_3_address0(dataflow_in_loop_loo_U0_p_distMap_3_address0),
    .p_distMap_3_ce0(dataflow_in_loop_loo_U0_p_distMap_3_ce0),
    .p_distMap_3_d0(dataflow_in_loop_loo_U0_p_distMap_3_d0),
    .p_distMap_3_q0(p_distMap_3_q0),
    .p_distMap_3_we0(dataflow_in_loop_loo_U0_p_distMap_3_we0),
    .p_distMap_3_address1(dataflow_in_loop_loo_U0_p_distMap_3_address1),
    .p_distMap_3_ce1(dataflow_in_loop_loo_U0_p_distMap_3_ce1),
    .p_distMap_3_d1(dataflow_in_loop_loo_U0_p_distMap_3_d1),
    .p_distMap_3_q1(32'd0),
    .p_distMap_3_we1(dataflow_in_loop_loo_U0_p_distMap_3_we1),
    .p_distMap_4_address0(dataflow_in_loop_loo_U0_p_distMap_4_address0),
    .p_distMap_4_ce0(dataflow_in_loop_loo_U0_p_distMap_4_ce0),
    .p_distMap_4_d0(dataflow_in_loop_loo_U0_p_distMap_4_d0),
    .p_distMap_4_q0(p_distMap_4_q0),
    .p_distMap_4_we0(dataflow_in_loop_loo_U0_p_distMap_4_we0),
    .p_distMap_4_address1(dataflow_in_loop_loo_U0_p_distMap_4_address1),
    .p_distMap_4_ce1(dataflow_in_loop_loo_U0_p_distMap_4_ce1),
    .p_distMap_4_d1(dataflow_in_loop_loo_U0_p_distMap_4_d1),
    .p_distMap_4_q1(32'd0),
    .p_distMap_4_we1(dataflow_in_loop_loo_U0_p_distMap_4_we1),
    .rays_TDATA(dataflow_in_loop_loo_U0_rays_TDATA),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .yaw_TVALID(yaw_TVALID),
    .yaw_TREADY(dataflow_in_loop_loo_U0_yaw_TREADY),
    .i1_0_ap_vld(1'b0),
    .y_TVALID(y_TVALID),
    .y_TREADY(dataflow_in_loop_loo_U0_y_TREADY),
    .x_TVALID(x_TVALID),
    .x_TREADY(dataflow_in_loop_loo_U0_x_TREADY),
    .orig_x_ap_vld(orig_x_ap_vld),
    .orig_y_ap_vld(orig_y_ap_vld),
    .map_width_ap_vld(map_width_ap_vld),
    .map_height_ap_vld(map_height_ap_vld),
    .map_resolution_ap_vld(map_resolution_ap_vld),
    .maxRange_ap_vld(maxRange_ap_vld),
    .ap_start(dataflow_in_loop_loo_U0_ap_start),
    .rays_TVALID(dataflow_in_loop_loo_U0_rays_TVALID),
    .rays_TREADY(rays_TREADY),
    .ap_done(dataflow_in_loop_loo_U0_ap_done),
    .ap_ready(dataflow_in_loop_loo_U0_ap_ready),
    .ap_idle(dataflow_in_loop_loo_U0_ap_idle),
    .ap_continue(dataflow_in_loop_loo_U0_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_input_count <= 32'd0;
    end else begin
        if ((~(loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_loo_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= (loop_dataflow_input_count + 32'd1);
        end else if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_loo_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_output_count <= 32'd0;
    end else begin
        if ((~(loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_loo_U0_ap_continue == 1'b1) & (dataflow_in_loop_loo_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= (loop_dataflow_output_count + 32'd1);
        end else if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_loo_U0_ap_continue == 1'b1) & (dataflow_in_loop_loo_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= 32'd0;
        end
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_loo_U0_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == 32'd0) & (ap_start == 1'b0) & (dataflow_in_loop_loo_U0_ap_idle == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_loo_U0_ap_ready == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~(loop_dataflow_output_count == bound_minus_1) | (ap_continue == 1'b1))) begin
        dataflow_in_loop_loo_U0_ap_continue = 1'b1;
    end else begin
        dataflow_in_loop_loo_U0_ap_continue = 1'b0;
    end
end

assign ap_sync_continue = ap_continue;

assign ap_sync_done = dataflow_in_loop_loo_U0_ap_done;

assign ap_sync_ready = dataflow_in_loop_loo_U0_ap_ready;

assign bound_minus_1 = (n_particles - 32'd1);

assign dataflow_in_loop_loo_U0_ap_start = ap_start;

assign dataflow_in_loop_loo_U0_i1_0 = loop_dataflow_input_count;

assign dataflow_in_loop_loo_U0_start_full_n = 1'b1;

assign dataflow_in_loop_loo_U0_start_write = 1'b0;

assign p_distMap_0_address0 = dataflow_in_loop_loo_U0_p_distMap_0_address0;

assign p_distMap_0_address1 = 18'd0;

assign p_distMap_0_ce0 = dataflow_in_loop_loo_U0_p_distMap_0_ce0;

assign p_distMap_0_ce1 = 1'b0;

assign p_distMap_0_d0 = 32'd0;

assign p_distMap_0_d1 = 32'd0;

assign p_distMap_0_we0 = 1'b0;

assign p_distMap_0_we1 = 1'b0;

assign p_distMap_1_address0 = dataflow_in_loop_loo_U0_p_distMap_1_address0;

assign p_distMap_1_address1 = 18'd0;

assign p_distMap_1_ce0 = dataflow_in_loop_loo_U0_p_distMap_1_ce0;

assign p_distMap_1_ce1 = 1'b0;

assign p_distMap_1_d0 = 32'd0;

assign p_distMap_1_d1 = 32'd0;

assign p_distMap_1_we0 = 1'b0;

assign p_distMap_1_we1 = 1'b0;

assign p_distMap_2_address0 = dataflow_in_loop_loo_U0_p_distMap_2_address0;

assign p_distMap_2_address1 = 18'd0;

assign p_distMap_2_ce0 = dataflow_in_loop_loo_U0_p_distMap_2_ce0;

assign p_distMap_2_ce1 = 1'b0;

assign p_distMap_2_d0 = 32'd0;

assign p_distMap_2_d1 = 32'd0;

assign p_distMap_2_we0 = 1'b0;

assign p_distMap_2_we1 = 1'b0;

assign p_distMap_3_address0 = dataflow_in_loop_loo_U0_p_distMap_3_address0;

assign p_distMap_3_address1 = 18'd0;

assign p_distMap_3_ce0 = dataflow_in_loop_loo_U0_p_distMap_3_ce0;

assign p_distMap_3_ce1 = 1'b0;

assign p_distMap_3_d0 = 32'd0;

assign p_distMap_3_d1 = 32'd0;

assign p_distMap_3_we0 = 1'b0;

assign p_distMap_3_we1 = 1'b0;

assign p_distMap_4_address0 = dataflow_in_loop_loo_U0_p_distMap_4_address0;

assign p_distMap_4_address1 = 18'd0;

assign p_distMap_4_ce0 = dataflow_in_loop_loo_U0_p_distMap_4_ce0;

assign p_distMap_4_ce1 = 1'b0;

assign p_distMap_4_d0 = 32'd0;

assign p_distMap_4_d1 = 32'd0;

assign p_distMap_4_we0 = 1'b0;

assign p_distMap_4_we1 = 1'b0;

assign rays_TDATA = dataflow_in_loop_loo_U0_rays_TDATA;

assign rays_TVALID = dataflow_in_loop_loo_U0_rays_TVALID;

assign x_TREADY = dataflow_in_loop_loo_U0_x_TREADY;

assign y_TREADY = dataflow_in_loop_loo_U0_y_TREADY;

assign yaw_TREADY = dataflow_in_loop_loo_U0_yaw_TREADY;

endmodule //dataflow_parent_loop_1
