// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "traffic_gen.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic traffic_gen::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic traffic_gen::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> traffic_gen::ap_ST_fsm_state1 = "1";
const sc_lv<4> traffic_gen::ap_ST_fsm_state2 = "10";
const sc_lv<4> traffic_gen::ap_ST_fsm_state3 = "100";
const sc_lv<4> traffic_gen::ap_ST_fsm_state4 = "1000";
const sc_lv<32> traffic_gen::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> traffic_gen::ap_const_lv32_1 = "1";
const sc_lv<32> traffic_gen::ap_const_lv32_2 = "10";
const sc_lv<32> traffic_gen::ap_const_lv32_3 = "11";
const bool traffic_gen::ap_const_boolean_1 = true;

traffic_gen::traffic_gen(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_generate_req_fu_36 = new generate_req("grp_generate_req_fu_36");
    grp_generate_req_fu_36->ap_clk(ap_clk);
    grp_generate_req_fu_36->ap_rst(ap_rst_n_inv);
    grp_generate_req_fu_36->ap_start(grp_generate_req_fu_36_ap_start);
    grp_generate_req_fu_36->ap_done(grp_generate_req_fu_36_ap_done);
    grp_generate_req_fu_36->ap_idle(grp_generate_req_fu_36_ap_idle);
    grp_generate_req_fu_36->ap_ready(grp_generate_req_fu_36_ap_ready);
    grp_generate_req_fu_36->stream_in_V_TDATA(stream_in_V_TDATA_int);
    grp_generate_req_fu_36->stream_in_V_TVALID(stream_in_V_TVALID_int);
    grp_generate_req_fu_36->stream_in_V_TREADY(grp_generate_req_fu_36_stream_in_V_TREADY);
    grp_generate_req_fu_36->stream_out_V_TDATA(grp_generate_req_fu_36_stream_out_V_TDATA);
    grp_generate_req_fu_36->stream_out_V_TVALID(grp_generate_req_fu_36_stream_out_V_TVALID);
    grp_generate_req_fu_36->stream_out_V_TREADY(grp_generate_req_fu_36_stream_out_V_TREADY);
    grp_generate_req_fu_36->n_trans(n_trans);
    regslice_both_stream_in_V_U = new regslice_both<32>("regslice_both_stream_in_V_U");
    regslice_both_stream_in_V_U->ap_clk(ap_clk);
    regslice_both_stream_in_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_stream_in_V_U->data_in(stream_in_V_TDATA);
    regslice_both_stream_in_V_U->vld_in(stream_in_V_TVALID);
    regslice_both_stream_in_V_U->ack_in(regslice_both_stream_in_V_U_ack_in);
    regslice_both_stream_in_V_U->data_out(stream_in_V_TDATA_int);
    regslice_both_stream_in_V_U->vld_out(stream_in_V_TVALID_int);
    regslice_both_stream_in_V_U->ack_out(stream_in_V_TREADY_int);
    regslice_both_stream_in_V_U->apdone_blk(regslice_both_stream_in_V_U_apdone_blk);
    regslice_both_stream_out_V_U = new regslice_both<32>("regslice_both_stream_out_V_U");
    regslice_both_stream_out_V_U->ap_clk(ap_clk);
    regslice_both_stream_out_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_stream_out_V_U->data_in(grp_generate_req_fu_36_stream_out_V_TDATA);
    regslice_both_stream_out_V_U->vld_in(grp_generate_req_fu_36_stream_out_V_TVALID);
    regslice_both_stream_out_V_U->ack_in(stream_out_V_TREADY_int);
    regslice_both_stream_out_V_U->data_out(stream_out_V_TDATA);
    regslice_both_stream_out_V_U->vld_out(regslice_both_stream_out_V_U_vld_out);
    regslice_both_stream_out_V_U->ack_out(stream_out_V_TREADY);
    regslice_both_stream_out_V_U->apdone_blk(regslice_both_stream_out_V_U_apdone_blk);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( regslice_both_stream_out_V_U_apdone_blk );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( regslice_both_stream_out_V_U_apdone_blk );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_grp_generate_req_fu_36_ap_start);
    sensitive << ( grp_generate_req_fu_36_ap_start_reg );

    SC_METHOD(thread_grp_generate_req_fu_36_stream_out_V_TREADY);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( stream_out_V_TREADY_int );

    SC_METHOD(thread_stream_in_V_TREADY);
    sensitive << ( stream_in_V_TVALID );
    sensitive << ( regslice_both_stream_in_V_U_ack_in );

    SC_METHOD(thread_stream_in_V_TREADY_int);
    sensitive << ( grp_generate_req_fu_36_stream_in_V_TREADY );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_stream_out_V_TVALID);
    sensitive << ( regslice_both_stream_out_V_U_vld_out );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_generate_req_fu_36_ap_done );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( regslice_both_stream_out_V_U_apdone_blk );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0001";
    grp_generate_req_fu_36_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "traffic_gen_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, stream_in_V_TDATA, "(port)stream_in_V_TDATA");
    sc_trace(mVcdFile, stream_in_V_TVALID, "(port)stream_in_V_TVALID");
    sc_trace(mVcdFile, stream_in_V_TREADY, "(port)stream_in_V_TREADY");
    sc_trace(mVcdFile, stream_out_V_TDATA, "(port)stream_out_V_TDATA");
    sc_trace(mVcdFile, stream_out_V_TVALID, "(port)stream_out_V_TVALID");
    sc_trace(mVcdFile, stream_out_V_TREADY, "(port)stream_out_V_TREADY");
    sc_trace(mVcdFile, n_trans, "(port)n_trans");
    sc_trace(mVcdFile, prob_req, "(port)prob_req");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, grp_generate_req_fu_36_ap_start, "grp_generate_req_fu_36_ap_start");
    sc_trace(mVcdFile, grp_generate_req_fu_36_ap_done, "grp_generate_req_fu_36_ap_done");
    sc_trace(mVcdFile, grp_generate_req_fu_36_ap_idle, "grp_generate_req_fu_36_ap_idle");
    sc_trace(mVcdFile, grp_generate_req_fu_36_ap_ready, "grp_generate_req_fu_36_ap_ready");
    sc_trace(mVcdFile, grp_generate_req_fu_36_stream_in_V_TREADY, "grp_generate_req_fu_36_stream_in_V_TREADY");
    sc_trace(mVcdFile, grp_generate_req_fu_36_stream_out_V_TDATA, "grp_generate_req_fu_36_stream_out_V_TDATA");
    sc_trace(mVcdFile, grp_generate_req_fu_36_stream_out_V_TVALID, "grp_generate_req_fu_36_stream_out_V_TVALID");
    sc_trace(mVcdFile, grp_generate_req_fu_36_stream_out_V_TREADY, "grp_generate_req_fu_36_stream_out_V_TREADY");
    sc_trace(mVcdFile, grp_generate_req_fu_36_ap_start_reg, "grp_generate_req_fu_36_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, regslice_both_stream_out_V_U_apdone_blk, "regslice_both_stream_out_V_U_apdone_blk");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, regslice_both_stream_in_V_U_apdone_blk, "regslice_both_stream_in_V_U_apdone_blk");
    sc_trace(mVcdFile, stream_in_V_TDATA_int, "stream_in_V_TDATA_int");
    sc_trace(mVcdFile, stream_in_V_TVALID_int, "stream_in_V_TVALID_int");
    sc_trace(mVcdFile, stream_in_V_TREADY_int, "stream_in_V_TREADY_int");
    sc_trace(mVcdFile, regslice_both_stream_in_V_U_ack_in, "regslice_both_stream_in_V_U_ack_in");
    sc_trace(mVcdFile, stream_out_V_TREADY_int, "stream_out_V_TREADY_int");
    sc_trace(mVcdFile, regslice_both_stream_out_V_U_vld_out, "regslice_both_stream_out_V_U_vld_out");
#endif

    }
    mHdltvinHandle.open("traffic_gen.hdltvin.dat");
    mHdltvoutHandle.open("traffic_gen.hdltvout.dat");
}

traffic_gen::~traffic_gen() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_generate_req_fu_36;
    delete regslice_both_stream_in_V_U;
    delete regslice_both_stream_out_V_U;
}

void traffic_gen::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_generate_req_fu_36_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
            grp_generate_req_fu_36_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_generate_req_fu_36_ap_ready.read())) {
            grp_generate_req_fu_36_ap_start_reg = ap_const_logic_0;
        }
    }
}

void traffic_gen::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void traffic_gen::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void traffic_gen::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void traffic_gen::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void traffic_gen::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(regslice_both_stream_out_V_U_apdone_blk.read(), ap_const_logic_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void traffic_gen::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void traffic_gen::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(regslice_both_stream_out_V_U_apdone_blk.read(), ap_const_logic_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void traffic_gen::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void traffic_gen::thread_grp_generate_req_fu_36_ap_start() {
    grp_generate_req_fu_36_ap_start = grp_generate_req_fu_36_ap_start_reg.read();
}

void traffic_gen::thread_grp_generate_req_fu_36_stream_out_V_TREADY() {
    grp_generate_req_fu_36_stream_out_V_TREADY = (ap_CS_fsm_state3.read() & stream_out_V_TREADY_int.read());
}

void traffic_gen::thread_stream_in_V_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, stream_in_V_TVALID.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_stream_in_V_U_ack_in.read()))) {
        stream_in_V_TREADY = ap_const_logic_1;
    } else {
        stream_in_V_TREADY = ap_const_logic_0;
    }
}

void traffic_gen::thread_stream_in_V_TREADY_int() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        stream_in_V_TREADY_int = grp_generate_req_fu_36_stream_in_V_TREADY.read();
    } else {
        stream_in_V_TREADY_int = ap_const_logic_0;
    }
}

void traffic_gen::thread_stream_out_V_TVALID() {
    stream_out_V_TVALID = regslice_both_stream_out_V_U_vld_out.read();
}

void traffic_gen::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(grp_generate_req_fu_36_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(regslice_both_stream_out_V_U_apdone_blk.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

void traffic_gen::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stream_in_V_TDATA\" :  \"" << stream_in_V_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stream_in_V_TVALID\" :  \"" << stream_in_V_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"stream_in_V_TREADY\" :  \"" << stream_in_V_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"stream_out_V_TDATA\" :  \"" << stream_out_V_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"stream_out_V_TVALID\" :  \"" << stream_out_V_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stream_out_V_TREADY\" :  \"" << stream_out_V_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"n_trans\" :  \"" << n_trans.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"prob_req\" :  \"" << prob_req.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

